# Generated by Django 3.0.7 on 2020-06-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_person_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='person',
        ),
        migrations.AlterField(
            model_name='person',
            name='skills',
            field=models.ManyToManyField(to='profiles.Skill'),
        ),
    ]
