# Generated by Django 3.0.7 on 2020-07-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='location',
            field=models.TextField(default=''),
        ),
    ]
